/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package organization;
import java.sql.Connection;
import java.sql.*;
import org.jfree.chart.*;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
/**
 *
 * @author HAMMAD TRADERS
 */
public class organisation extends javax.swing.JFrame {
Connection conn;
ResultSet rs;
PreparedStatement pst;
    /**
     * Creates new form organisation
     */
    public organisation() {
        initComponents();
        conn=Organization.connectDb();
          
           
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        performance = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jButton1.setText("Show Pie Chart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        performance.setBackground(new java.awt.Color(204, 217, 235));
        performance.setBorder(javax.swing.BorderFactory.createTitledBorder("Report"));
        performance.setLayout(new javax.swing.BoxLayout(performance, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Organization Employees Performance based on Age");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(performance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel1)))
                        .addGap(0, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(performance, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String sql="select W_hours from employees where age between 18 and 24";
           int hours1 =0;
           try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while(rs.next()){
            int hr = rs.getInt("W_hours");
            
            hours1+=hr;
            
        }
           }
           catch(Exception e){
               System.out.println("error occured"+e);
           }
           
           
            String sql1="select NOP from employees where age between 18 and 24";
           int nop1 =0;
           try{
        pst = conn.prepareStatement(sql1);
        rs = pst.executeQuery();
        
        while(rs.next()){
            int np = rs.getInt("NOP");
            
            nop1+=np;
            
        }
           }
           catch(Exception e){
               System.out.println("error occured"+e);
           }
           /////////////////////////////
            String sql3="select W_hours from employees where age between 25 and 34";
           int hours2 =0;
           try{
        pst = conn.prepareStatement(sql3);
        rs = pst.executeQuery();
        
        while(rs.next()){
            int hr = rs.getInt("W_hours");
            
            hours2+=hr;
            
        }
           }
           catch(Exception e){
               System.out.println("error occured"+e);
           }
        
             String sql4="select NOP from employees where age between 25 and 34";
           int nop2 =0;
           try{
        pst = conn.prepareStatement(sql4);
        rs = pst.executeQuery();
        
        while(rs.next()){
            int np = rs.getInt("NOP");
            
            nop2+=np;
            
        }
           }
           catch(Exception e){
               System.out.println("error occured"+e);
           }
           ///////////////////////////////
            String sql5="select W_hours from employees where age between 35 and 44";
           int hours3 =0;
           try{
        pst = conn.prepareStatement(sql5);
        rs = pst.executeQuery();
        
        while(rs.next()){
            int hr = rs.getInt("W_hours");
            
            hours3+=hr;
            
        }
           }
           catch(Exception e){
               System.out.println("error occured"+e);
           }
        
             String sql6="select NOP from employees where age between 35 and 44";
           int nop3 =0;
           try{
        pst = conn.prepareStatement(sql6);
        rs = pst.executeQuery();
        
        while(rs.next()){
            int np = rs.getInt("NOP");
            
            nop3+=np;
            
        }
           }
           catch(Exception e){
               System.out.println("error occured"+e);
           }
           
           ///////////////////////////////////////////////////
              String sql7="select W_hours from employees where age between 45 and 55";
           int hours4 =0;
           try{
        pst = conn.prepareStatement(sql7);
        rs = pst.executeQuery();
        
        while(rs.next()){
            int hr = rs.getInt("W_hours");
            
            hours4+=hr;
            
        }
           }
           catch(Exception e){
               System.out.println("error occured"+e);
           }
        
             String sql8="select NOP from employees where age between 45 and 55";
           int nop4 =0;
           try{
        pst = conn.prepareStatement(sql8);
        rs = pst.executeQuery();
        
        while(rs.next()){
            int np = rs.getInt("NOP");
            
            nop4+=np;
            
        }
           }
           catch(Exception e){
               System.out.println("error occured"+e);
           }
        
           int total_hours = hours1+hours2+hours3+hours4;
           int total_proj = nop1+nop2+nop3+nop4;
           
           
           
           float percent1 = (((float)nop1/total_proj)*100) + (((float)hours1/total_hours)*100);//64
           float percent2 = (((float)nop2/total_proj)*100) + (((float)hours2/total_hours)*100);//54

           float percent3 = (((float)nop3/total_proj)*100) + (((float)hours3/total_hours)*100);//26

           float percent4 = (((float)nop4/total_proj)*100) + (((float)hours4/total_hours)*100);//50
           
           
           float total = percent1+percent2+percent3+percent4;
           
           float f1 = (percent1/total)*100; 
           float f2 = (percent2/total)*100;
           float f3 = (percent3/total)*100;
           float f4 = (percent4/total)*100;
           
           
         
           DefaultPieDataset dcd = new DefaultPieDataset();
           dcd.setValue("Age: 18--24", f1);
           dcd.setValue("Age: 25--34", f2);
           dcd.setValue("Age: 35--44", f3);
           dcd.setValue("Age: 45--55", f4);
          
           JFreeChart chart = ChartFactory.createPieChart("performance of Employees", dcd, true, true, true);
           PiePlot p =(PiePlot)chart.getPlot();
//          
           ChartFrame frame = new ChartFrame("Pie Chart",chart);
           
           frame.setVisible(true);
           frame.setSize(600, 500);
          
         
           
           
//           
//           JFreeChart jchart = ChartFactory.createBarChart("Performance of Employee", "Age Range", "performance level", dcd, PlotOrientation.VERTICAL, true,true,false);
//           CategoryPlot plot = jchart.getCategoryPlot();
//           plot.setRangeGridlinePaint(Color.black);
//           
//           ChartFrame chartfrm = new ChartFrame("Performance of Employee",jchart,true);
//           chartfrm.setVisible(true);
//           chartfrm.setSize(400, 300);
//           
//           ChartPanel chartPanel = new ChartPanel(jchart);
//           
//           performance.removeAll();
//           performance.add(chartPanel);
//           chartPanel.updateUI();
//           
//           chartfrm.setVisible(false);
//           
           
           
           
           
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
   
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(organisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(organisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(organisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(organisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new organisation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel performance;
    // End of variables declaration//GEN-END:variables
}
